import { Application, Router, staticFileRoutes, Status } from "./deps.ts";
import { getLikes, updateLikes } from "./service.ts";
import vento from "ventojs";

const app = new Application();

const env = vento();

// deno-lint-ignore no-explicit-any
async function updateLikesHandler(ctx: any) {
  ctx.response.headers.set("Content-Type", "text/html");
  const likes = await updateLikes(ctx);
  const result = await env.run("server/views/likes.vto", { likes: likes, state: 'done' });
  ctx.response.body = result.content;
  ctx.response.status = Status.OK;
}

// deno-lint-ignore no-explicit-any
async function getLikesHandler(ctx: any) {
  const { likes, alreadyLiked } = await getLikes(ctx);
  ctx.response.headers.set("Content-Type", "text/html");

  // checked if already liked by this client
  if (alreadyLiked === true) {
    const result = await env.run("server/views/likes.vto", { likes: likes, state: 'done'});
    ctx.response.body = result.content;
    ctx.response.status = Status.OK;
  } else {
    const result = await env.run("server/views/likes.vto", { likes: likes, state: 'like' });
    ctx.response.body = result.content;
    ctx.response.status = Status.OK;
  }
}

// deno-lint-ignore no-explicit-any
async function getUnLikesHandler(ctx: any) {
  ctx.response.headers.set("Content-Type", "text/html");
  const likes = await updateLikes(ctx);
  const result = await env.run("server/views/likes.vto", { likes: likes, state: 'unlike' });
  ctx.response.body = result.content;
  ctx.response.status = Status.OK;
}

const router = new Router();

router
  .get("/likes.html", getLikesHandler)
  .post("/unlikes.html", getUnLikesHandler)
  .post("/likes.html", updateLikesHandler)

app.use(router.routes());

// checks for static routes (real html files generated by 11ty in the _site directory) and uses them if they exist
app.use(staticFileRoutes);

app.use(router.allowedMethods());

app.use((ctx) => {
  ctx.response.body = "nuppers";
  ctx.response.status = Status.NotFound;
});

app.addEventListener("listen", () => {
  console.log("✨ Server ready! Browse at http://localhost:8000 ✨");
});

await app.listen({ port: 8000 });
